/**
 * plugins/dw-lifecycle/src/scope-discovery/deprecation-report.ts
 *
 * Markdown + summary + JSON formatters for the deprecation scan. The
 * CLI calls these twice — once for stdout (operator scanning) and once
 * for the committed artifact at
 * `.dw-lifecycle/scope-discovery/deprecation-queue.md` when `--write`
 * is passed.
 *
 * Output shape (one block per status):
 *
 *   # Deprecation queue
 *
 *   _Total: <N> deprecated file(s); <B> blocked; <S> safe to delete._
 *
 *   ## Blocked (importers > 0): <B>
 *
 *   ### <path>
 *
 *   - deprecation: `@deprecated <message>` (or `// DEPRECATED: <message>`)
 *   - importers: <count>
 *     - `<importer-path>:<line>`
 *     - …
 *
 *   ## Safe to delete (importers === 0): <S>
 *
 *   - `<path>` — `@deprecated <message>`
 *
 * Empty scan (no deprecated files) emits a one-line "nothing to track"
 * placeholder so the committed artifact at `deprecation-queue.md`
 * never becomes blank.
 *
 * # DRY
 *
 * Both output paths (stdout text + markdown artifact) render from the
 * same builder. Keeping one builder enforces parity by construction.
 *
 * Ported from the audiocontrol pilot's
 * `tools/scope-discovery/deprecation-report.ts`. Path default rewritten
 * to the dw-lifecycle `.dw-lifecycle/scope-discovery/` convention.
 */

import type {
  DeprecatedFile,
  DeprecatedImporter,
  ScanResult,
} from './deprecation-scan.js';

/**
 * Default destination path for the committed artifact (relative to
 * the scan root). Mirrors `editor-symmetry-report.ts`'s placement under
 * `.dw-lifecycle/scope-discovery/` per the project's canonical config
 * directory (Finding AUDIT-20260525-03).
 */
export const ARTIFACT_PATH = '.dw-lifecycle/scope-discovery/deprecation-queue.md';

export function renderMarkdown(result: ScanResult): string {
  const total = result.blocked.length + result.safeToDelete.length;
  const lines: string[] = [];
  lines.push('# Deprecation queue');
  lines.push('');
  lines.push(intro());
  lines.push('');
  if (total === 0) {
    lines.push(
      'No `@deprecated` JSDoc tags or `// DEPRECATED:` markers found in the source tree. ' +
        'When a refactor extracts a primitive and the legacy file is marked deprecated, ' +
        'it surfaces here with the count of remaining importers (blocked) or under the ' +
        'safe-to-delete queue (importers === 0).',
    );
    lines.push('');
    return lines.join('\n') + '\n';
  }
  lines.push(
    `_Total: ${total} deprecated file(s); ${result.blocked.length} blocked; ` +
      `${result.safeToDelete.length} safe to delete._`,
  );
  lines.push('');
  lines.push(`## Blocked (importers > 0): ${result.blocked.length}`);
  lines.push('');
  if (result.blocked.length === 0) {
    lines.push('_None._');
    lines.push('');
  } else {
    for (const file of result.blocked) {
      lines.push(renderBlockedFile(file));
      lines.push('');
    }
  }
  lines.push(`## Safe to delete (importers === 0): ${result.safeToDelete.length}`);
  lines.push('');
  if (result.safeToDelete.length === 0) {
    lines.push('_None._');
    lines.push('');
  } else {
    for (const file of result.safeToDelete) {
      lines.push(renderSafeFile(file));
    }
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

function intro(): string {
  return (
    'This file is regenerated by `dw-lifecycle check-deprecations --write` from the source ' +
    'tree. Rows are files with a file-level deprecation marker (top-of-file JSDoc ' +
    '`@deprecated` or `// DEPRECATED:` line comment within the first 20 lines). For each ' +
    'file, the scanner counts external importers (any TS/TSX file importing the deprecated ' +
    "path via its `@/` alias or a relative path matching its basename). Files with zero " +
    'importers are safe to delete; files with importers are blocked until every consumer ' +
    'migrates.'
  );
}

function renderBlockedFile(file: DeprecatedFile): string {
  const lines: string[] = [];
  lines.push(`### \`${file.path}\``);
  lines.push('');
  lines.push(`- deprecation: ${formatMarker(file)}`);
  lines.push(`- importers: ${file.importers.length}`);
  for (const importer of file.importers) {
    lines.push(`    - \`${importer.path}:${importer.line}\``);
  }
  return lines.join('\n');
}

function renderSafeFile(file: DeprecatedFile): string {
  return `- \`${file.path}\` — ${formatMarker(file)}`;
}

function formatMarker(file: DeprecatedFile): string {
  const prefix = file.markerKind === 'jsdoc' ? '`@deprecated' : '`// DEPRECATED:';
  const body = file.message.length === 0 ? '' : ` ${file.message}`;
  return `${prefix}${body}\``;
}

/**
 * Plain-text summary line for stdout. Operators scanning the terminal
 * get the headline counts without parsing the markdown.
 */
export function summaryLine(result: ScanResult): string {
  const total = result.blocked.length + result.safeToDelete.length;
  if (total === 0) {
    return `check-deprecations: 0 deprecated files; nothing to track.`;
  }
  return (
    `check-deprecations: ${total} deprecated file(s); ` +
    `${result.blocked.length} blocked, ${result.safeToDelete.length} safe to delete.`
  );
}

/**
 * Structured JSON for downstream tooling. The wire shape is stable so
 * an orchestrator can consume it without parsing markdown.
 *
 * `deprecation_count` is preserved alongside `total` for backwards
 * compatibility with the pre-port shell's JSON output (the shell
 * emitted `deprecation_count: 0` and nothing else); a consumer that
 * was tracking the shell's empty-registry response continues to read
 * the same key.
 */
export function renderJson(result: ScanResult): string {
  return JSON.stringify(
    {
      total: result.blocked.length + result.safeToDelete.length,
      deprecation_count: result.blocked.length + result.safeToDelete.length,
      filesVisited: result.filesVisited,
      blocked: result.blocked.map(serializeFile),
      safeToDelete: result.safeToDelete.map(serializeFile),
    },
    null,
    2,
  );
}

function serializeFile(file: DeprecatedFile): Record<string, unknown> {
  return {
    path: file.path,
    message: file.message,
    markerKind: file.markerKind,
    importers: file.importers.map(serializeImporter),
  };
}

function serializeImporter(importer: DeprecatedImporter): Record<string, unknown> {
  return { path: importer.path, line: importer.line };
}
