/**
 * plugins/dw-lifecycle/src/scope-discovery/doctor-rules/catalog-entry-missing-status.ts
 *
 * Phase 11 Task 2 — Doctor rule: detect operator-curated catalog
 * entries that were authored without an explicit `status:` field.
 *
 * # Why this rule exists
 *
 * The Loop foundation (Phase 11 Task 2) adds `status:` + `provenance:`
 * to every registered catalog entry. Backward-compatible: registries
 * that omit the fields continue to parse — the parser synthesizes
 * `status: blessed` + an install-seed provenance for pre-Loop entries.
 *
 * But synthesis hides the operator's intent. An entry without `status:`
 * is enforced as `blessed`, which may not be what the operator wants
 * (they may want `tracked-holdout` or `pending` while triaging).
 * This rule surfaces every entry-omitting-status as a warning so the
 * operator gets an explicit nudge to declare status when they next
 * touch the file.
 *
 * # Scope
 *
 * Checks three operator-curated catalogs:
 *   - .dw-lifecycle/scope-discovery/anti-patterns.yaml
 *   - .dw-lifecycle/scope-discovery/adopter-manifests.yaml
 *   - .dw-lifecycle/scope-discovery/clones.yaml
 *
 * The pattern-matrix override (.dw-lifecycle/scope-discovery/
 * pattern-matrix-patterns.yaml) is intentionally NOT checked — it's
 * an override of the built-in catalog (whose entries already declare
 * status via the typed `BUILTIN_PATTERNS`), and the rule would
 * generate noise on every adopter override that hasn't yet been
 * migrated. A separate rule can surface that case if it becomes a
 * pain point.
 *
 * The deprecation-queue.yaml is also not checked — its entries are
 * generated by the scanner (not hand-authored), so the status would
 * always be synthesized.
 *
 * # Finding shape
 *
 * One finding per entry without a `status:` field, naming the file
 * + the entry's id + suggesting the explicit declaration. The rule
 * is non-blocking (severity: warning).
 *
 * Cross-cut with `scope-discovery-schema-stale`: that rule warns when
 * `schemaVersion:` is missing; this rule warns when individual entries
 * miss `status:`. The two are independent — a registry with
 * `schemaVersion: 1` can still have entries omitting `status:`.
 */

import { existsSync, readFileSync } from 'node:fs';
import { parse as parseYaml } from 'yaml';
import { join } from 'node:path';
import { errorMessage, isPlainObject } from '../util/typeguards.js';
import type {
  DoctorRuleCheck,
  DoctorRuleOptions,
  ScopeDoctorFinding,
} from './types.js';

const RULE_ID = 'catalog-entry-missing-status';
const CONFIG_DIR_REL = '.dw-lifecycle/scope-discovery';

interface CheckedRegistry {
  readonly file: string;
  readonly topLevelKey: string;
  /** Display label for the entry kind (one of "anti-pattern", "adopter-manifest", "clone"). */
  readonly label: string;
}

const CHECKED_REGISTRIES: ReadonlyArray<CheckedRegistry> = [
  { file: 'anti-patterns.yaml', topLevelKey: 'anti_patterns', label: 'anti-pattern' },
  {
    file: 'adopter-manifests.yaml',
    topLevelKey: 'adopter_manifests',
    label: 'adopter-manifest',
  },
  { file: 'clones.yaml', topLevelKey: 'clones', label: 'clone' },
];

function entryDisplayId(raw: unknown, index: number, label: string): string {
  if (!isPlainObject(raw)) return `${label}[${index}] (malformed)`;
  const id = raw['id'];
  if (typeof id === 'string' && id.length > 0) return id;
  return `${label}[${index}] (no id)`;
}

function entryMissingStatus(raw: unknown): boolean {
  if (!isPlainObject(raw)) return false;
  const status = raw['status'];
  return status === undefined || status === null;
}

export const check: DoctorRuleCheck = async (
  opts: DoctorRuleOptions,
): Promise<readonly ScopeDoctorFinding[]> => {
  const configDir = join(opts.repoRoot, CONFIG_DIR_REL);
  if (!existsSync(configDir)) {
    // scope-discovery-config-missing covers this case.
    return [];
  }
  const findings: ScopeDoctorFinding[] = [];
  for (const reg of CHECKED_REGISTRIES) {
    const path = join(configDir, reg.file);
    if (!existsSync(path)) continue;
    let text: string;
    try {
      text = readFileSync(path, 'utf8');
    } catch (err) {
      findings.push({
        rule: RULE_ID,
        severity: 'warning',
        message: `${path}: failed to read for status check (${errorMessage(err)}).`,
      });
      continue;
    }
    let parsed: unknown;
    try {
      parsed = parseYaml(text);
    } catch {
      // Shape errors are surfaced by the dedicated schema-violation
      // rules; we don't double-report here.
      continue;
    }
    if (!isPlainObject(parsed)) continue;
    const entries = parsed[reg.topLevelKey];
    if (!Array.isArray(entries)) continue;
    const missing: string[] = [];
    entries.forEach((entry: unknown, idx: number) => {
      if (entryMissingStatus(entry)) {
        missing.push(entryDisplayId(entry, idx, reg.label));
      }
    });
    if (missing.length === 0) continue;
    // One finding per registry summarizing the missing-status entries.
    // We aggregate to keep doctor output readable; each id is
    // enumerated in the message so the operator can fix them in one
    // pass.
    findings.push({
      rule: RULE_ID,
      severity: 'warning',
      message:
        `${path}: ${missing.length} ${reg.label}(s) without explicit \`status:\`. ` +
        `Synthesized default is \`status: blessed\` (actively enforced). ` +
        `Add an explicit \`status:\` field to each entry to declare intent. ` +
        `Missing on: ${missing.join(', ')}. ` +
        `See plugins/dw-lifecycle/src/scope-discovery/util/catalog-status.ts for the status vocabulary.`,
    });
  }
  return findings;
};
